### PR TITLE
Add context for all API interactions

### PR DESCRIPTION
**Pull request by jamieaitken**
Hey folks 👋 I've added a [context](https://pkg.go.dev/context#pkg-overview) counterpart for all public API functions so that requests will be cancelled if the client cancels.

My reasoning for creating a counterpart instead of changing the existing functions was to avoid breaking changes and as for the approach, I took inspiration from how the standard library dealt with [http.NewRequest](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/net/http/request.go;l=812) and [http.NewRequestWithContext](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/net/http/request.go;l=838)

### CODE REVIEW

**Comment by jamieaitken** [comment]
@armando-rodriguez-cko Would you mind having a look at this when you get 10mins please?

**Comment by armando-rodriguez-cko** [comment]
Thank you @jamieaitken!, we will take a look.

**Comment by jamieaitken** [comment]
Hey @armando-rodriguez-cko 👋 Was wondering if you have had time to look over the PR?

**Comment by armando-rodriguez-cko** [comment]
@jamieaitken we are reviewing, sorry for the delay.

**Comment by armando-rodriguez-cko** [comment]
Hi @jamieaitken, we are still reviewing.

**Comment by AlexCuse** [comment]
This is a great way to provide instrumentation on the underlying HTTP client as well.

**Comment by armando-rodriguez-cko** [comment]
Hi @jamieaitken, we are still reviewing. We don't forget it

**Comment by jamieaitken** [comment]
Hey @armando-rodriguez-cko 👋  Wondering if you got anywhere with this?

**Comment by armando-rodriguez-cko** [comment]
We are finishing the review, we are sorry. We will try to finish it in two weeks.

**Comment by jamieaitken** [comment]
Hey @armando-rodriguez-cko 👋 Do we still intend to merge this? If not, I can close the PR

**Comment by jamieaitken** [comment]
Hey @armando-rodriguez-cko 👋  Are we any closer to getting this merged? If it's easier, I can limit this PR to only add Context for NAS interactions?

**Comment by armando-rodriguez-cko** [comment]
Hi @jamieaitken , I apologise for the delay, I am merging your branch in a beta branch to test it better

**Comment by rockwelln** [comment]
hello @armando-rodriguez-cko :wave: I wonder if you still plan to merge it to master?

**Comment by jamieaitken** [comment]
Hey @armando-rodriguez-cko 👋  could we look into getting this merged into main please

**Pull request merged**
